language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t chefanitha/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true chefanitha/react-test npm run test -- --coverage

after_success:
    - docker build -t chefanitha/multi-client ./client
    - docker build -t chefanitha/multi-nginx ./nginx
    - docker build -t chefanitha/multi-server ./server
    - docker build -t chefanitha/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    # Take those images and push them to docker hub
    - docker push chefanitha/multi-client
    - docker push chefanitha/multi-nginx
    - docker push chefanitha/multi-server
    - docker push chefanitha/multi-worker

# deploy:
#     provider: elasticbeanstalk
#     region: us-east-1
#     app: "docker-react"
#     env: "DockerReact-env"
#     bucket_name: "elasticbeanstalk-us-east-1-212967381570"
#     bucket_path: "docker-react"
#     on:
#         branch: "master"
#     access_key_id: "$AWS_ACCESS_KEY"
#     secret_access_key: "$AWS_SECRET_KEY"